version: '3.7'

services:
    microservice:
        build:
            context: .
        image: vectorserver
        container_name: vectorserver
        restart: unless-stopped
        ports:
            - "5000:5000"
        entrypoint: ["python", "-m", "uvicorn", "vectorServer.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
        
    redis:
        image: redis:6
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf